""" Prompt: Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. """

sum = 2
i = 1
j = 2
below = True

while below:
    i =  i + j
    j = j + i
    # finds the next two values in the sequences
    
    if i > 4000000:
        # i is the lower number, so if i is greater than 4 million, j will be too 
        # but if j is greater than 4 million, i might not be, meaning a value may be missed out
        below = False
        continue

    if i % 2 == 0:
        sum += i
    if j % 2 == 0:
        sum += j
    # adds the even values to the sum

print(sum)
